version: '2'
services:
  react:
    container_name: react
    image: node:14.13.1
    user: root:root
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../main:/home/node/app
    ports:
      - "8180:3000"
    tty: true
    restart: always
    # command: bash -c "npm install --global http-server webpack && npm run build -f && npm start"
    # command: npm start
    command: yarn start
    
networks:
  iotplt-private:
    external:
      name: develop-private
